name: Checks

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linked_issue:
    name: Jira
    runs-on: ubuntu-latest
    steps:
      - uses: openstax/jira-linked-action@v0.1.15
        with:
          jira_site: openstax
          jira_project: DISCO
          jira_email: ${{ secrets.JiraEmail }}
          jira_token: ${{ secrets.JiraToken }}
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn
      - run: yarn lint
      - run: yarn test
