name: Build

on:
  deployment:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: setup
        run: |
          prefix="${{ github.deployment.ref }}"
          [ "$prefix" == "refs/heads/main" ] && prefix="main" || prefix="$prefix/${{ github.deployment.sha }}"
          echo "::set-output name=prefix::$prefix"

      - name: set deployment status to in progress
        id: start_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ github.deployment.id }}
          environment: dev
          environment_url: https://openstax.github.io/${{ github.repository }}/${{ steps.setup.outputs.prefix }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: in_progress
          mediaType: '{"previews": ["flash", "ant-man"]}'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - id: build
        run: |
          prefix="${{ steps.setup.outputs.prefix }}"
          yarn
          yarn ladle build --base "/ui-components/$prefix/"
          mkdir -p "./$prefix"
          mv ./docs/* "./$prefix"

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false

      - name: push
        run: |
          git config --global user.name 'staxly'
          git config --global user.email 'staxly@users.noreply.github.com'
          git add "./${{ steps.setup.outputs.prefix }}"
          git commit -m "building ${{ steps.setup.outputs.prefix }}"
          git push

