name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - id: build
        run: |
          prefix="${{ github.event.ref }}/${{ github.event.after }}"
          yarn
          yarn ladle build --base "/ui-components/$prefix/"
          mkdir -p "./$prefix"
          mv ./docs/* "./$prefix"
          echo "::set-output name=prefix::$prefix"

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false

      - name: push
        run: |
          git add "./${{ steps.build.outputs.prefix }}"
          git commit -m "building ${{ steps.build.outputs.prefix }}"
          git push
